#!/bin/sh
set -e

echo "Running Jekyll build..."
bundle exec jekyll build

echo "Running HTMLProofer..."
bundle exec htmlproofer ./_site --check-html --check-sri --url-ignore "https://www.linkedin.com/in/dominic-correlli-756847237/"

echo "Running RuboCop..."
bundle exec rubocop -D --config .rubocop.yml

echo "Running HTML validation script..."
bundle exec script/validate-html

echo "Build and test steps completed successfully."